from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path
import sys
import tempfile
import unittest


sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from doc_agent.agent import DocumentationAgent
from doc_agent.cli import main as doc_agent_main
from doc_agent.executor import ToolExecutionError, ToolExecutor
from doc_agent.tools import ToolContext, build_tool_registry


class DocumentationAgentTests(unittest.TestCase):
    def test_tool_metadata_describes_parameters(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            executor = ToolExecutor(
                build_tool_registry(ToolContext(project_root=Path(tmp)))
            )

            metadata = {tool["tool_name"]: tool for tool in executor.metadata()}

            self.assertEqual(
                set(metadata),
                {
                    "list_python_files",
                    "read_file",
                    "write_doc_file",
                    "list_doc_files",
                    "read_doc_file",
                    "delete_doc_file",
                },
            )
            self.assertEqual(
                metadata["read_file"]["parameters"]["required"],
                ["file_path"],
            )
            self.assertEqual(
                metadata["write_doc_file"]["parameters"]["required"],
                ["file_name", "content"],
            )

    def test_executor_validates_action_arguments(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            executor = ToolExecutor(
                build_tool_registry(ToolContext(project_root=Path(tmp)))
            )

            with self.assertRaises(ToolExecutionError):
                executor.execute({"tool_name": "read_file", "args": {}})

            with self.assertRaises(ToolExecutionError):
                executor.execute(
                    {
                        "tool_name": "read_file",
                        "args": {"file_path": "src/example.py", "extra": "nope"},
                    }
                )

            with self.assertRaises(ToolExecutionError):
                executor.execute({"tool_name": "missing_tool", "args": {}})

    def test_agent_generates_markdown_docs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp)
            source_dir = project_root / "src"
            source_dir.mkdir()
            (source_dir / "example.py").write_text(
                '''"""Example module."""


class Greeter:
    """Greets people."""

    def hello(self, name: str) -> str:
        """Return a greeting."""
        return f"Hello {name}"


def add(left: int, right: int) -> int:
    """Add two numbers."""
    return left + right
''',
                encoding="utf-8",
            )

            context = ToolContext(project_root=project_root)
            executor = ToolExecutor(build_tool_registry(context))
            result = DocumentationAgent(executor).run()

            doc_path = project_root / "docs" / "example.md"
            content = doc_path.read_text(encoding="utf-8")

            self.assertEqual(result.files_documented, 1)
            self.assertEqual(result.source_files_found, 1)
            self.assertIn("docs/example.md", result.docs_written)
            self.assertIn("Generated by doc-agent", content)
            self.assertIn("# `example`", content)
            self.assertIn("### `Greeter`", content)
            self.assertIn("### `add(left: int, right: int) -> int`", content)

    def test_incremental_mode_writes_only_changed_docs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp)
            source_dir = project_root / "src"
            source_dir.mkdir()
            source_file = source_dir / "example.py"
            source_file.write_text(
                '"""Example module."""\n\n\ndef original() -> str:\n    """Original docs."""\n    return "ok"\n',
                encoding="utf-8",
            )

            context = ToolContext(project_root=project_root)
            executor = ToolExecutor(build_tool_registry(context))
            agent = DocumentationAgent(executor)

            first_result = agent.run(incremental=True)
            second_result = agent.run(incremental=True)
            source_file.write_text(
                '"""Example module."""\n\n\ndef changed() -> str:\n    """Changed docs."""\n    return "ok"\n',
                encoding="utf-8",
            )
            third_result = agent.run(incremental=True)
            content = (project_root / "docs" / "example.md").read_text(encoding="utf-8")

            self.assertEqual(first_result.docs_written, ["docs/example.md"])
            self.assertEqual(second_result.docs_written, [])
            self.assertEqual(third_result.docs_written, ["docs/example.md"])
            self.assertIn("changed() -> str", content)

    def test_check_mode_reports_outdated_docs_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp)
            source_dir = project_root / "src"
            source_dir.mkdir()
            (source_dir / "example.py").write_text(
                '"""Example module."""\n',
                encoding="utf-8",
            )

            context = ToolContext(project_root=project_root)
            executor = ToolExecutor(build_tool_registry(context))
            result = DocumentationAgent(executor).run(check=True)

            self.assertTrue(result.has_pending_changes)
            self.assertEqual(result.outdated_docs, ["docs/example.md"])
            self.assertFalse((project_root / "docs" / "example.md").exists())

    def test_prune_stale_removes_deleted_source_docs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp)
            source_dir = project_root / "src"
            source_dir.mkdir()
            keep_file = source_dir / "keep.py"
            stale_file = source_dir / "stale.py"
            keep_file.write_text('"""Keep."""\n', encoding="utf-8")
            stale_file.write_text('"""Stale."""\n', encoding="utf-8")

            context = ToolContext(project_root=project_root)
            executor = ToolExecutor(build_tool_registry(context))
            agent = DocumentationAgent(executor)
            agent.run()

            stale_file.unlink()
            check_result = agent.run(check=True)
            prune_result = agent.run(incremental=True, prune_stale=True)

            self.assertIn("docs/stale.md", check_result.stale_docs)
            self.assertIn("docs/stale.md", prune_result.stale_docs_deleted)
            self.assertTrue((project_root / "docs" / "keep.md").exists())
            self.assertFalse((project_root / "docs" / "stale.md").exists())

    def test_cli_check_returns_nonzero_when_docs_are_out_of_date(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp)
            source_dir = project_root / "src"
            source_dir.mkdir()
            (source_dir / "example.py").write_text(
                '"""Example module."""\n',
                encoding="utf-8",
            )

            with redirect_stdout(StringIO()):
                result = doc_agent_main(
                    ["--project-root", str(project_root), "run", "--check"]
                )

            self.assertEqual(result, 1)


if __name__ == "__main__":
    unittest.main()
